import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { FC } from 'react';

import { DEVELOPMENT_MODE } from '#bazaar/constants/env.constants';
import { LocaleLayoutProps } from '#bazaar/types/props/localeLayout.props';

import 'normalize.css';
import '#bazaar/theme/css/tailwind.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Bazaar'
};

const RootLayout: FC<LocaleLayoutProps> = async ({ children, params }) => {
  const messages = await getMessages();

  return (
    <html lang={params.locale}>
      <head>
        <meta content="notranslate" name="google" />
        {
          DEVELOPMENT_MODE && (
            <meta content="noindex, nofollow" name="robots" />
          )
        }
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          { children }
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
